<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>New Bank</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
  </head>
  <body>
    <H3><a href="/">New Bank</a></H3>
      <br>
    <form method="post">
      <label for="name">Name:</label><br>
      <input type="text" id="name" name="name" required minlength="3" maxlength="50"><br>
      <input type="submit" value="Create">
    </form>
  </body>
</html>